ENTRY = { rule | comment };
_ = {" " | "\t" | "\n"};
comment = "/", "/", {"\c"};
rule = _, name, _, "=", list, ";", _, [comment];
name = "\a", { "\w" };
list = item | ( { item, "," }, item );
item = _, name | term | alter | option | repeat | group, _;
term = "\"", "\S", {"\S"} ,"\"";
group = "(", list, ")";
alter = item, "|" , item;
option = "[", list, "]";
repeat = "{", list, "}";
